package lang_ext

var CommonLanguageExt = map[string]string{
	".cfg":          "Config",
	".go":           "Golang",
	".java":         "Java",
	".py":           "Python",
	".lua":          "Lua",
	".j2":           "Jinja",
	".jinja":        "Jinja",
	".c":            "C",
	".cc":           "C++",
	".hh":           "C++ Header",
	".h":            "C/C++ Header",
	".cgi":          "cgi",
	".cpp":          "C++",
	".hpp":          "C++",
	".rs":           "Rust",
	".rb":           "Ruby",
	".cjs":          "JavaScript",
	".js":           "JavaScript",
	".ts":           "TypeScript",
	".tsx":          "TS React",
	".vue":          "Vue",
	".json":         "Json",
	".yaml":         "Yaml",
	".yml":          "Yaml",
	".ini":          "Ini",
	".md":           "Markdown",
	".sh":           "Shell",
	".htm":          "Html",
	".html":         "Html",
	".css":          "CSS",
	".pl":           "Perl",
	".perl":         "Perl",
	".xml":          "XML",
	".proto":        "Grpc",
	".txt":          "Text",
	".rst":          "RST",
	".ipynb":        "Jupyter",
	".m4":           "M4",
	".am":           "AutoMake",
	".texi":         "TEXINFO",
	".po":           "PO File",
	".awk":          "awk",
	".rc":           "Windows Resource File",
	".bmp":          "Bitmap",
	".tex":          "TeX",
	".php":          "PHP",
	".conf":         "Configuration File",
	".ac":           "Autoconf Script",
	".nsi":          "NSIS Script",
	".asc":          "Key File",
	".patch":        "Patch File",
	".sgml":         "Markup Language File",
	".xaml":         "XML",
	".pyx":          "pyx",
	".cuh":          "Cuda Header",
	".cu":           "Cuda Source",
	".bat":          "bat",
	".toml":         "Toml",
	".jsonl":        "Jsonl",
	".Dockerfile":   "Dockerfile",
	".env":          "Environment Variables",
	".dockerignore": "Ignore Files",
}
