package lang_ext

var CommonLanguageExt = map[string]string{
	".cfg":   "Config",
	".go":    "Golang",
	".java":  "Java",
	".py":    "Python",
	".lua":   "Lua",
	".j2":    "Jinja",
	".c":     "C",
	".cc":    "C++",
	".hh":    "C++ Header",
	".h":     "C/C++ Header",
	".cu":    "cuda",
	".cgi":   "cgi",
	".cpp":   "C++",
	".js":    "JavaScript",
	".ts":    "TypeScript",
	".vue":   "Vue",
	".json":  "Json",
	".yaml":  "Yaml",
	".yml":   "Yaml",
	".ini":   "Ini",
	".md":    "Markdown",
	".sh":    "Shell",
	".html":  "Html",
	".css":   "CSS",
	".pl":    "Perl",
	".perl":  "Perl",
	".xml":   "XML",
	"Grpc":   "Grpc",
	".proto": "Grpc",
	".txt":   "Text",
	".ipynb": "Jupyter",
	".m4":    "M4",
	".am":    "AutoMake",
	".texi":  "TEXINFO",
	".po":    "PO File",
	".awk":   "awk",
	".rc":    "Windows Resource File",
	".bmp":   "Bitmap",
	".tex":   "TeX",
	".php":   "PHP",
	".conf":  "Configuration File",
	".ac":    "Autoconf Script",
	".nsi":   "NSIS Script",
	".asc":   "Key File",
	".patch": "Patch File",
	".sgml":  "Markup Language File",
	".xaml":  "XML",
	".pyx":   "pyx",
}
